name: azen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - matplotlib
  - openpyxl
  - notebook
  - jpype1
  - nltk
  - scikit-learn
  - tqdm
  - pip:
      - flask
      - jinja2
      - beautifulsoup4
      - selenium
      - webdriver-manager
      - requests
      - lxml
      - html5lib
      - pymysql
      - konlpy
      - wordcloud
      - gunicorn
      - googlemaps
      - geopy
      - googlegenai